### ISSUE TITLE
ptaction.yaml reader

### ISSUE THREAD

**Issue by FireSquid6** [pwrtool/powertool#14]
ptaction files should look like:
```yaml
---
name: my-cool-action
steps:
- type: step
  describe: my-step
  kit: user/kit
  tool: default
  args:
    key: value
  get:
    var-outputted-from-scratch: name
- type: condition
  condition: "{name} === 21"
  'true':
  - type: step
    describe: my-step
    kit: user/kit
    tool: default
    args:
      key: value
    get:
      var-outputted-from-scratch: name
  'false':
  - type: exit
```

More documentation will be created about them
